import type { CSSProperties } from 'react';
import type { ThemeTokens } from './tokens';

export function themeToCssVars(theme: ThemeTokens): CSSProperties {
  const { colors, fontFamily, fontSize, space, radius, borderWidth, zIndex } = theme;

  return {
    ['--tui-bg' as string]: colors.bg,
    ['--tui-surface0' as string]: colors.surface0,
    ['--tui-surface1' as string]: colors.surface1,
    ['--tui-surface2' as string]: colors.surface2,
    ['--tui-overlay0' as string]: colors.overlay0,
    ['--tui-overlay1' as string]: colors.overlay1,
    ['--tui-text' as string]: colors.text,
    ['--tui-subtext0' as string]: colors.subtext0,
    ['--tui-subtext1' as string]: colors.subtext1,
    ['--tui-accent' as string]: colors.accent,
    ['--tui-accent-muted' as string]: colors.accentMuted,
    ['--tui-green' as string]: colors.green,
    ['--tui-yellow' as string]: colors.yellow,
    ['--tui-red' as string]: colors.red,
    ['--tui-peach' as string]: colors.peach,
    ['--tui-teal' as string]: colors.teal,
    ['--tui-mauve' as string]: colors.mauve,
    ['--tui-blue' as string]: colors.blue,
    ['--tui-border' as string]: colors.border,
    ['--tui-focus' as string]: colors.focus,
    ['--tui-selection' as string]: colors.selection,
    ['--tui-danger' as string]: colors.danger,
    ['--tui-warning' as string]: colors.warning,
    ['--tui-success' as string]: colors.success,
    ['--tui-info' as string]: colors.info,
    ['--tui-font' as string]: fontFamily,
    ['--tui-fs-xs' as string]: fontSize.xs,
    ['--tui-fs-sm' as string]: fontSize.sm,
    ['--tui-fs-md' as string]: fontSize.md,
    ['--tui-fs-lg' as string]: fontSize.lg,
    ['--tui-fs-xl' as string]: fontSize.xl,
    ['--tui-space-0' as string]: space[0],
    ['--tui-space-1' as string]: space[1],
    ['--tui-space-2' as string]: space[2],
    ['--tui-space-3' as string]: space[3],
    ['--tui-space-4' as string]: space[4],
    ['--tui-space-5' as string]: space[5],
    ['--tui-space-6' as string]: space[6],
    ['--tui-space-7' as string]: space[7],
    ['--tui-space-8' as string]: space[8],
    ['--tui-radius-none' as string]: radius.none,
    ['--tui-radius-sm' as string]: radius.sm,
    ['--tui-radius-md' as string]: radius.md,
    ['--tui-border-width' as string]: borderWidth,
    ['--tui-z-dropdown' as string]: String(zIndex.dropdown),
    ['--tui-z-modal' as string]: String(zIndex.modal),
    ['--tui-z-toast' as string]: String(zIndex.toast),
    ['--tui-z-tooltip' as string]: String(zIndex.tooltip),
    color: colors.text,
    backgroundColor: colors.bg,
    fontFamily,
    fontSize: fontSize.md,
  } as CSSProperties;
}
